name: Release

permissions:
  contents: write

on:
  release:
    types: [published]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: linux-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install rustup target
        run: rustup target add ${{ matrix.target }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: cargo build --release --target ${{ matrix.target }}
      - name: Show the output
        run: ls -l target/${{ matrix.target }}/release
      - name: Compress the binary
        working-directory: target/${{ matrix.target }}/release
        run: tar -czf sjupdate-${{ matrix.target }}.tar.gz sjupdate
      - name: Upload the artifact
        uses: actions/upload-artifact@v4
        with:
          name: sjupdate-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/sjupdate-${{ matrix.target }}.tar.gz

  release:
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-unknown-linux-gnu]
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download the artifact
        uses: actions/download-artifact@v4
        with:
          name: sjupdate-${{ matrix.target }}
      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          files: sjupdate-${{ matrix.target }}.tar.gz