name: Test

on:
  pull_request:
    paths:
      - 'src/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install clippy and rustfmt
      run: rustup component add clippy rustfmt
    - name: Format
      run: cargo fmt --all -- --check
    - name: Clippy
      run: cargo clippy -- -D warnings
    - name: Test
      run: cargo test